---
title: "strings"
author: "Selvin Carrillo"
date: "created: November 16, 2022; updated: November 16, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, warning=FALSE, message=FALSE}
# clean workspace 
rm(list = list())

# load libraries 
library(tidyverse) # contains stringr package 
library(tidytext) # more advanced operations for strings 
library(janitor)
```

## 
```{r}
# read in my chlorophyll fluorescence data to practice 
x <- read_csv("data/2022TGGChl.csv") %>% 
     clean_names() %>% 
     dplyr::select(qr_code) %>% 
     separate(qr_code, 
              into = c("block", "trt", "pot", "genotype"), 
              sep = "/")
x %>% 
     filter(str_detect(trt, "^aa4")) # str_detect to subset 

x %>% 
     mutate(genotype_N16 = str_count(genotype, "^N16|26$")) # word counts (end in 26)



# fruits data 
data("fruit")
fruit
```

```{r}
text <- c("Because I could not stop for Death -", 
          "He kindly stopped for me -",
          "The Carriage held but just Ourselves -",
          "and Immortality")

```

